[package]
name = "tauri-start-solid"
version = "0.0.0"
description = "A Tauri application built with Tauri, SolidJS, and TypeScript"
authors = ["you"]
license = "MIT or Apache-2.0"
repository = "http://github.com/riipandi/tauri-start-solid"
rust-version = "1.77"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_start_solid_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
dotenv-build = "^0.1.1"
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
# Tauri dependencies
tauri = { version = "2.2.5", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-http = "2.3.0"
tauri-plugin-os = "2.2.0"
tauri-plugin-positioner = { version = "2.2.0", features = ["tray-icon"] }
tauri-plugin-process = "2.2.0"
tauri-plugin-shell = "2.2.0"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Logging
anyhow = "1.0"

# Used to call the macOS native API
[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26.0"
objc = "0.2.7"
